### ISSUE TITLE
fetch: true not working 

### ISSUE THREAD

**Issue by ssteffl** [RallyTools/rally-node#12]
i am currently doing fetch:['true'] as a workaround

**Comment by krmorse** [comment]
fetch: true is sort of frowned upon because of performance, but it is pretty convenient.  i don't remember explicitly no supporting it but i'm also not surprised it doesn't just work out of the box.  i'll look into it...

**Comment by ssteffl** [comment]
oh. i wasn't aware that was frowned upon. nevermind then.

**Comment by krmorse** [comment]
partially because it's inefficient to fetch a bunch of fields if you don't need them.  also true does not fetch any sub objects or collections so you'll likely be missing some data you'd want anyway...
