### ISSUE TITLE
Get Request

### ISSUE THREAD

**Issue by ljkmchale** [RallyTools/rally-node#14]
I had to modify the restapi.js file to include 2 items for the options.  Rally supports order and pagesize in the get request.  We need to make sure that this is included.  I added the below code. 

RestApi.prototype.get = function(options, callback) {
    var deferred = Q.defer();
     options = _.merge({
     	order: '',
        pageSize: 200
    }, options);
    this.request.get(_.merge({
            url: refUtils.getRelative(options.ref),
            qs: {
				order: options.order,
				pagesize: options.pageSize
			}
        }, options.requestOptions,
        optionsToRequestOptions(options)), function(error, result) {
        if (error) {
            deferred.reject(error);
        } else {
            deferred.resolve({
                Errors: result.Errors,
                Warnings: result.Warnings,
                Object: _.omit(result, ['Errors', 'Warnings'])
            });
        }
    });
    return deferred.promise.nodeify(callback);
};

**Comment by krmorse** [comment]
I'm curious why this is needed.  Get is generally used for reading a single specific object, so the parameters you mention are not necessary.  Is there are a reason you can't use the query method?  What endpoint are you trying to read?

**Comment by ljkmchale** [comment]
There is many times when you read a testcase and then need to get a list of all the steps (input and expectations) so create and interface to the really system and display them.  When you loop thru the testcase steps they could (and are) not in an order. And, there could be many pages.  So i need to be able to expand the pagesize and order the steps.  So using the GET does bring back a single object, but that object has many items.

**Comment by krmorse** [comment]
I figured you were probably loading a collection.  You should use the query method as in this example (which loads the Children collection of stories from a parent story): https://github.com/RallyTools/rally-node/blob/master/examples/query.promise.js#L17

**Comment by ljkmchale** [comment]
Have tried using a query method for this, but for getting the steps it does not seem to work.

**Comment by ljkmchale** [comment]
Also, rally's docs tell us to do it this way.

**Comment by krmorse** [comment]
Hmm, this should work:

    restApi.query({
        ref: "https://rally1.rallydev.com/slm/webservice/v2.0/testcase/12345/Steps",
        start: 1,
        limit: Infinity,
        order: 'StartIndex',
        fetch: ['Input', 'ExpectedResult']
    });

Can you try that and if that fails reply back with the specific error?
Also, can you tell me where the docs state to do it the way you are trying to do it?
