### ISSUE TITLE
Unable to query feature by state

### ISSUE THREAD

**Issue by fredrickgu** [RallyTools/rally-node#19]
Hello, thanks for developing this node library, right now I am using it for query features for our project management, but I can't query feature by a specific state:

```
restApi.query({
    type : 'portfolioitem/feature',
    fetch : ['FormattedID','ObjectID','State','Owner','Release','Name'],
    start : 1,
    limit : 200,
    query : queryUtils.where('State', '!=', 'Done'),
    scope : {
        workspace : "/workspace/...",
        project : "/project/...",
        up : false,
        down : true
    },
    requestOptions : {}
}).then(function (result) {}).fail(function(error){});
```

I tried other query condition like 'Name', 'LeafStoryCount', they all work, except State, it might not be a issue, but do you know what is the correct way of querying by feature state? thanks a lot!

**Comment by fredrickgu** [comment]
I found the solution, the query should be 
`queryUtils.where('State.Name', '!=', 'Done'),`

**Comment by krmorse** [comment]
Cool, glad you figured it out!
