### ISSUE TITLE
Rally Lookback API - C# Issue

### ISSUE THREAD

**Issue by sukri7** [RallyTools/rally-node#25]
I am trying to get data from Rally LookBack API for my Rally Instance. My company instance is behind SSO and I have tried all the method of bypassing it with credentials, but nothing seems to be working.

In Lookback API, it is said that we can use an API key for authentication. So I tried the code below from POST Man, but I got the 500:Internal Server Error, with out any further information on the error. Can someone please help me with this. (Actually the actual response for this is "Error:500")

HttpWebRequest request = (HttpWebRequest)HttpWebRequest.Create(new Uri("https://rally1.rallydev.com/analytics/v2.0/service/rally/workspace/5985761382/artifact/snapshot/query.js?find='_ProjectHierarchy':12506089503,'__At':'current'}));
request.Method = WebRequestMethods.Http.Get;
request.Timeout = Timeout.Infinite;
request.Accept = "application/json";

request.Headers.Add("Authorization", "Basic " + "Rally API Key");
WebResponse response = request.GetResponse();

It is very very urgent. Please help

**Comment by krmorse** [comment]
This question is probably better asked on [http://stackoverflow.com/questions/tagged/rally](http://stackoverflow.com/questions/tagged/rally) or the .net toolkit page, but I'll answer it here.  None of our toolkits officially support the Lookback API, so I'm not sure what other issues you'll run into.  That being said, API Keys are passed using a header called zsessionid.  That might get you a little farther...
