### ISSUE TITLE
Fetch results sorted by a field

### ISSUE THREAD

**Issue by hdattada** [RallyTools/rally-node#26]
I am trying to fetch iterations and I am wondering if there is a field which specifies how to order the results? I want to sort the result based on StartDate field. Below is my quert

`query({
        type: 'iterations',
        fetch: ['Name', 'StartDate', 'EndDate'],
        scope: {
          workspace: this.workspace,
          project: this.config.default_rally_path,
          up: false,
          down: false
        },
        query: query
      })`

**Comment by krmorse** [comment]
Sure, check out the `order` property in this example in the docs: https://github.com/RallyTools/rally-node/wiki/User-Guide#query-a-type

**Comment by hdattada** [comment]
Thanks @krmorse
