### ISSUE TITLE
Is it possible to tell the query object to only fetch resultCount

### ISSUE THREAD

**Issue by hdattada** [RallyTools/rally-node#27]
I am trying to fetch testcases with various filters,but more often than not I am only interested in the resultcount than the actual object. Is it possible to get the TotalResultCount properties without the actual object returned?

**Comment by krmorse** [comment]
The best you can do is set the pageSize parameter to 1.  That may be slightly faster since it's a smaller response for the server to render and send over the wire, but the database query time will probably be the same still.
