### ISSUE TITLE
HTTP 401 Error

### ISSUE THREAD

**Issue by infn8** [RallyTools/rally-node#30]
Not sure if this is an error for this library or not but here goes:

When connecting i use this code

```
const rally = require('rally');

rc = rally({
	user: 'user@domain.ext',
	pass: 'xxxxxxxx',
	apiKey: token
});
```
Using the `token` Which i get by going here:

https://rally1.rallydev.com/slm/webservice/v2.0/security/authorize

with my username and password.  I then run this

```
rc.get({
	fetch: ['FormattedID', 'USXXXXX'], //fields to fetch
	scope: {
		workspace: '/workspace/YYYYYYYYYYYd' 
	},
}).then(function(result) {
		console.log(result);
}).catch(function(errors) {
	 console.log(errors);
});
```
Where `YYYYYYYYYYYd` is my real workspace ID and `USXXXXX` is a real User Story on that workspace.  I get response that says:

```
Error 401 Full Authentication is required to access this resource 
HTTP ERROR 401
Problem Accessing /slm/webservice/v2.0null. Reason:
Full Authentication is required to access this resource
Powered by Jetty
```
Am I missing something?

**Comment by krmorse** [comment]
A couple things. First- you should either use username/password OR an api key, but not both.  You shouldn't need to worry about the CSRF token or the /security/authorize endpoint- that will be handled transparently by the toolkit once you are authenticated.

An api key may be obtained by going to https://rally1.rallydev.com/login

It seems like you're trying to find a story by FormattedID.  In order to do that you'll need to use the `query` method.  The error you're getting is because the `get` method expects a `ref` property of the object to read (/defect/12345 for example)

Something like this should work for you:

    restApi.query({
        type: 'hierarchicalrequirement', //the type to query
        fetch: ['FormattedID'], //the fields to retrieve
        query: queryUtils.where('FormattedID', '=', 'US12345)
    }).then().catch()...

**Comment by vijendra-impetus** [comment]
I am trying to update the note section of a user story. Below is my code : 

var rally = require('rally'),
    queryUtils = rally.util.query;
    refUtils = rally.util.ref;
    restApi = rally({
        user: username,
        pass: password,
        apiVersion: 'v2.0',
        server: 'https://rally1.rallydev.com', 
    }, function (error, result) {
            if (error) {
                console.log('Failed to access Rally server:', error);
            }
    });

Above code is working as expected am able to update the note section of userstory or defect. But when try to use the same with "apiKey". I got error " Item with ID <story number> not found".

With username and password things working fine but not with apiKey. can you please help?

**Comment by krmorse** [comment]
Can you post your full code?  I think the code above is just a snippet.

**Comment by vijendra-impetus** [comment]
console.log('\nUpdating rally comments');

var args = process.argv.slice(2);
    username = args[0].split(":")[0];
    password = args[0].split(":")[1];
    item = args[1];
    comments = args[2];
    updatedNotes = args[2];

if (item.substr(0,2) === 'DE') {
    itemType = 'defect';
    console.log('Defect: ' + args[1]);
    console.log('Comments to be added: ' + comments + '\n');
} else if (item.substr(0,2) === 'US') {
    itemType = 'hierarchicalrequirement';
    console.log('User story: ' + args[1]);
    console.log('Comments to be added: ' + comments + '\n');
} else {
    try {
        throw new Error('Please provide a correct defect or user story id to update.\nSample command: node app.js \'username:password\' \'defectId\' \'Comments to be updated\'');
    } catch (error) {
        console.log('Failed while updating comments:', error.message);
        return false;
    }
}

var rally = require('rally'),
    queryUtils = rally.util.query;
    refUtils = rally.util.ref;
    restApi = rally({
       user: username, //required if no api key, defaults to process.env.RALLY_USERNAME
       pass: password, //required if no api key, defaults to process.env.RALLY_PASSWORD
       server: 'https://rally1.rallydev.com',  //this is the default and may be omitted
    }, function (error, result) {
            if (error) {
                console.log('Failed to access Rally server:', error);
            }
    });

function getNotes() {
    return restApi.query({
        type: itemType,
        fetch: ['Notes'], 
        query: queryUtils.where('FormattedID', '=', item)
    });
}

function updateNotes(result) {
    console.log(result);
    if (!result || !result.Results || result.Results.length === 0) {
        throw new Error('Item with ID ' + item + ' not found');
    }
    notes = result.Results[0].Notes;
    if (notes) {
        updatedNotes = notes + '<br><div>' + comments + '</div>';
    }
console.log(updatedNotes);
    return restApi.update({
        ref: refUtils.getRelative(result.Results[0]._ref),
        data: {
            Notes: updatedNotes //the data with which to update the specified object
        }
    });
}

function onSuccess(result) {
    console.log('Successfully updated comments for ' + item);
}

function onError(errors) {
    console.log('Failed while updating comments for ' + item, errors);
}

getNotes().
    then(updateNotes).
    then(onSuccess).
    fail(onError)

Above is the complete code.

**Comment by vijendra-impetus** [comment]
Above code is working fine as i am giving username and password but when i try to comment username and password and give apiKey, then i got error.

**Comment by vijendra-impetus** [comment]
Hi @krmorse did you got a chance to look in to this?

thanks in advance for the help.

**Comment by krmorse** [comment]
The code looks ok in general... Are you sure the api key is valid?

**Comment by vijendra-impetus** [comment]
@krmorse ,

Yes the API key is valid.

**Comment by Asha-arabhanvi** [comment]
Hi 
@krmorse 
I am trying to access data of rally using Rally npm package. and i am getting this authentication issue though i am giving correct credentials and api keys

Error:
Error 401 Full authentication is required to access this resource
HTTP ERROR 401
Problem accessing /slm/webservice/v2.0/defects. Reason:
 Full authentication is required to access this resource
what is the solution , is there any proxy to be set?

Please help me in this
Thanks in Advance
