### ISSUE TITLE
Difficulty listing all available workspaces

### ISSUE THREAD

**Issue by davepreston** [RallyTools/rally-node#32]
There doesn't seem to be a way to get the available workspaces. 
When I query with ```type: 'workspace'``` I get only the default workspace. 
That's also what I get when I hit the workspace endpoint directly:
https://rally1.rallydev.com/slm/webservice/v2.0/workspace

From my research, to get all the workspaces I have access to I need to use the subscription endpoint. 
https://rally1.rallydev.com/slm/webservice/v2.0/Subscription/MY-SUBSCRIPTION-ID-HERE/Workspaces

Is that possible with this library?

**Comment by krmorse** [comment]
You should be able to do this.  Check out the querying a collection section in the user guide: https://github.com/RallyTools/rally-node/wiki/User-Guide#query-a-collection

You also may be able to do `type: workspaces` instead.

**Comment by davepreston** [comment]
Thanks for your quick response. It looks like my confusion was around the use of ```ref``` vs ```type``` during querying. I am able to get the results I need by using ```ref: '/Subscription/MY-SUBSCRIPTION-ID-HERE/Workspaces'```

Thanks again.
