### ISSUE TITLE
restApi calls do not work after converting them to Node8 promisify

### ISSUE THREAD

**Issue by vinchauhan** [RallyTools/rally-node#34]
For example :  Writing the query method this way is returning an error that request is undefined.

const query = util.promisify(rallyApi.query)
    query({
        type: 'hierarchicalrequirement', //the type to query
        // start: 1, //the 1-based start index, defaults to 1
        // pageSize: 2, //the page size (1-200, defaults to 200)
        // limit: 10, //the maximum number of results to return- enables auto paging
        order: 'Rank', //how to sort the results
        fetch: ['FormattedID', 'Name', 'ScheduleState', 'Children'], //the fields to retrieve
        // query: queryUtils.where('DirectChildrenCount', '>', 0), //optional filter
        // scope: {
        //     workspace: '/workspace/1234' //specify to query entire workspace
        //     project: '/project/2345' //specify to query a specific project
        //     up: false //true to include parent project results, false otherwise
        //     down: true //true to include child project results, false otherwise
        // },
        requestOptions: {} //optional additional options to pass through to request
    }).then(result => {
        console.log(result.Results);
    }).catch(err => {
        console.log(err);
    });

TypeError: Cannot read property 'request' of undefined
    at query (C:\bla-bla\node_modules\rally\dist\restapi.js:307:31)
    at query (internal/util.js:227:26)
    at Object.customHierarchical (C:\bla-bla\rally\custom-query-hierarchical.ts:8:5)
    at C:\bla-bla\commander.ts:110:13
    at <anonymous>

**Comment by krmorse** [comment]
rally-node already returns promises for all of the methods.  they support both syntaxes.  promisify should be totally unnecessary here isn't it?

**Comment by vinchauhan** [comment]
Actually it works by creating a promise es6 way, new Promise () {}.

Thanks for replying.
