### ISSUE TITLE
Unable to create Object

### ISSUE THREAD

**Issue by amiya-pattnaik** [RallyTools/rally-node#36]
Hi,
I am unable to create testcase or defect through the create method. It throws error `Error: Not authorized to create: TestCase`
Please note that, I do have `Editor` access in RALLY for that project/workspace and I can bale create new testcase / defect through manually. Below is the code.

//working but need to check API again

function createTestcase() {
  restApi.create({
    type: 'TestCase', //the type to create
    data: {
        Name: 'MyTestCase123' //the data with which to populate the new object
    },
    fetch: ['FormattedID'],  //the fields to be returned on the created object
    scope: {
        workspace: '/workspace/11772661382' 
    },
    requestOptions: {}        
}, function(error, result) {
    if(error) {
        console.log(error);
    } else {
        console.log(result.Object);
    }
  });
}

Please note, I wrote few custom command to update the test case and defect it works fine. But create () method does not work.

Thanks in advance

**Comment by krmorse** [comment]
Hmm, overall that code looks ok.  It doesn't look like you're specifying a project, which is probably why it's failing.  What if you add Project: '/project/12345' in your data blob and try again?

**Comment by amiya-pattnaik** [comment]
Thanks Krmorse..
With this above info. I am able to create a test case at project lever. 
1. How can I create a testcase at story level ?
2. How can I create a defect at a test case level. I mean to create a defect based on the test case status and link to that testcase.

If so that are the specific OID (key:value) pair I need to add. Please suggest.
Thanks in advance

**Comment by amiya-pattnaik** [comment]
Here is my code for creating a defect and assigning to test cases. It throws error. Not authorised to create defect.

function addDefectToTestcase(testcaseID, defectName){
  //adds defect to a testcase (for example which is listed under the `Details for TC626066`)
  var _ref_hierarchical = '';
  request.query({
    type:     'TestCase',     //the type to query
    start:    1,              //the 1-based start index, defaults to 1
    pageSize: 2,              //the page size (1-200, defaults to 200)
    limit:    10,             //the maximum number of results to return- enables auto paging
    order:    'Rank',         //how to sort the results
    query:    queryUtils.where('FormattedID', '=', testcaseID),
  }, function(error, queryRes) {
        if(error) {
          console.log(error);
        } else {
          //console.log(queryRes);
          _ref_testcase = queryRes.Results[0]['_ref'].split('/testcase/')[1];
        }
        request.add ({
          ref: '/testcase/'+_ref_testcase, //the object which owns the collection- in this case the parent story
          collection: 'Defects',        //the name of the collection being added to
          data: [
              //{_ref: '/defect/DE75791'}, //add this existing defect
              {Name: defectName} //add a new defect
          ],
          //fetch: ['FormattedID', 'Name', 'State'], //the fields to retrieve in the results
          //requestOptions: {} //optional additional options to pass through to request
      }, function (error, result) {
            if(error) {
              console.log(error);
            } else {
              console.log('*** defect created for the testcase: '+testcaseID+' successfully ! ***');
            }
        });     //end of add block
    });         //end of query block
}

**Comment by krmorse** [comment]
Sure, Test case has a WorkProduct field which you can set to either a story or a defect.

    WorkProduct: '/hierarchicalrequirement/12345'

And Defect has a requirement field to link it to a story.

    Requirement: '/hierarchicalrequirement/12345'

Are you familiar with the wsapi docs?  You should be able to browse around and discover all the fields on the different object types: https://rally1.rallydev.com/slm/doc/webservice/

**Comment by amiya-pattnaik** [comment]
Hi Krmorse,
I tried below option for creating a test case as blow, but it throws error. while if I pass project info then it creates a testcase at project level

  scope: {
        //project: '/project/78493315800' //works fine for project UID
        WorkProduct: '/hierarchicalrequirement/12012345',  // does not work
       // Requirement: '/hierarchicalrequirement/12012345' // does not work
    },

Below is the  complete method
//working it creates test cases at the poject level
function createTestcase() {
  request.create({
    type: 'TestCase', //the type to create
    data: {
        Name: 'MyTestCase123' //the data with which to populate the new object
    },
    fetch: ['FormattedID'],  //the fields to be returned on the created object
    scope: {
        //project: '/project/7454933158123'
        WorkProduct: '/hierarchicalrequirement/12012345',
        Requirement: '/hierarchicalrequirement/12012345'
    },
    requestOptions: {}        //optional additional options to pass through to request
}, function(error, result) {
    if(error) {
        console.log(error);
    } else {
        console.log(result.Object);
    }
  });
}

**Comment by krmorse** [comment]
Those go in the data blob, since they are fields on the test case to be created.  Honestly, Project should go there too.

    data: {
        Project: '/project/12345,
        WorkProduct: '/hierarchicalrequirement/23456'
    }

**Comment by amiya-pattnaik** [comment]
Hi Krmorse,
Thanks for your help. I followed your suggestion it worked. 
Once a again a tons of thanks to you.

**Comment by krmorse** [comment]
👍  glad you got it!

**Comment by nkanteti** [comment]
I am unable to edit the Method for test case when coded through Rally API. it always picks up Manual
