### ISSUE TITLE
Question: Any way to "query" multiple "type"s?

### ISSUE THREAD

**Issue by ammmze** [RallyTools/rally-node#40]
Is there a way to query multiple types? Say I want to search for all user stories and defects for a given search term. Right now I'd probably fire off 2 requests, one for `defect` and one for `hierarchicalrequirement` and then combine the results. Though that doesn't work super great for pagination.

**Comment by krmorse** [comment]
Yes, you can query the `artifact` endpoint.  Both stories and defects inherit from artifact.  Just specify a `types` query string param:

    `/slm/webservice/v2.0/artifact?types=defect,hierarchicalrequirement&query=(Name contains "Foo")`

**Comment by ammmze** [comment]
Cool...thanks...i'll look into that. Sounds like i'll have to do that manually though, right? Or is there a way to doing it via `restApi.query`?

**Comment by krmorse** [comment]
It should work with restApi.query, you can use artifact just like any other type.

```
restApi.query({
    type: 'artifact',
    qs: {
        types: 'defect,hierarchicalrequirement'
    },
    // other options
});
```

**Comment by ammmze** [comment]
Perfect...makes sense :) thank you
